/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.fon.silab.gui;

import javax.swing.JOptionPane;
import rs.fon.silab.gui.party.PartiesForm;
import rs.fon.silab.gui.speech.SpeechesForm;
import rs.fon.silab.gui.session.SessionsForm;
import rs.fon.silab.gui.member.MemberForm;
import rs.fon.silab.start.ClientStart;

/**
 *
 * @author Branislav Vidojevic
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        String stringPort = null;
        while (stringPort == null || stringPort.isEmpty()) {
            stringPort = JOptionPane.showInputDialog(this, "Insert server port number to connect to.");
            try {
                int port = Integer.parseInt(stringPort);
                if (port < 1000 || port > 9999) {
                    stringPort = null;
                }
            } catch (Exception e) {
                stringPort = null;
            }
        }
        initComponents();
        int port = Integer.parseInt(stringPort);
        new ClientStart(port).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMembers = new javax.swing.JButton();
        btnParties = new javax.swing.JButton();
        btnSpeeches = new javax.swing.JButton();
        btnSessions = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnMembers = new javax.swing.JMenuItem();
        mnParties = new javax.swing.JMenuItem();
        mnSpeeches = new javax.swing.JMenuItem();
        mnSessions = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client parliament program");
        setResizable(false);

        btnMembers.setText("MEMBERS");
        btnMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMembersActionPerformed(evt);
            }
        });

        btnParties.setText("PARTIES");
        btnParties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartiesActionPerformed(evt);
            }
        });

        btnSpeeches.setText("SPEECHES");
        btnSpeeches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpeechesActionPerformed(evt);
            }
        });

        btnSessions.setText("SESSIONS");
        btnSessions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSessionsActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");

        mnMembers.setText("Members");
        mnMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMembersActionPerformed(evt);
            }
        });
        jMenu1.add(mnMembers);

        mnParties.setText("Parties");
        mnParties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPartiesActionPerformed(evt);
            }
        });
        jMenu1.add(mnParties);

        mnSpeeches.setText("Speeches");
        mnSpeeches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSpeechesActionPerformed(evt);
            }
        });
        jMenu1.add(mnSpeeches);

        mnSessions.setText("Sessions");
        mnSessions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSessionsActionPerformed(evt);
            }
        });
        jMenu1.add(mnSessions);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(btnMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnParties, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSpeeches, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSessions)
                .addGap(41, 41, 41))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMembers, btnParties, btnSessions, btnSpeeches});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnParties, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSpeeches, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSessions))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMembers, btnParties, btnSessions, btnSpeeches});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMembersActionPerformed
        startMemberForm();
    }//GEN-LAST:event_btnMembersActionPerformed

    private void mnMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMembersActionPerformed
        startMemberForm();
    }//GEN-LAST:event_mnMembersActionPerformed

    private void btnPartiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartiesActionPerformed
        startPartiesForm();
    }//GEN-LAST:event_btnPartiesActionPerformed

    private void mnPartiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPartiesActionPerformed
        startPartiesForm();
    }//GEN-LAST:event_mnPartiesActionPerformed

    private void btnSessionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSessionsActionPerformed
        startSessionsForm();
    }//GEN-LAST:event_btnSessionsActionPerformed

    private void mnSessionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSessionsActionPerformed
        startSessionsForm();
    }//GEN-LAST:event_mnSessionsActionPerformed

    private void btnSpeechesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpeechesActionPerformed
        startSpeechesForm();
    }//GEN-LAST:event_btnSpeechesActionPerformed

    private void mnSpeechesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSpeechesActionPerformed
        startSpeechesForm();
    }//GEN-LAST:event_mnSpeechesActionPerformed

    private void startMemberForm() {
        MemberForm memberForm = new MemberForm();
        memberForm.setLocationRelativeTo(null);
        memberForm.setVisible(true);
    }

    private void startPartiesForm() {
        PartiesForm partiesForm = new PartiesForm();
        partiesForm.setLocationRelativeTo(null);
        partiesForm.setVisible(true);
    }

    private void startSessionsForm() {
        SessionsForm sessionsForm = new SessionsForm();
        sessionsForm.setLocationRelativeTo(null);
        sessionsForm.setVisible(true);
    }

    private void startSpeechesForm() {
        SpeechesForm speechesForm = new SpeechesForm();
        speechesForm.setLocationRelativeTo(null);
        speechesForm.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMembers;
    private javax.swing.JButton btnParties;
    private javax.swing.JButton btnSessions;
    private javax.swing.JButton btnSpeeches;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnMembers;
    private javax.swing.JMenuItem mnParties;
    private javax.swing.JMenuItem mnSessions;
    private javax.swing.JMenuItem mnSpeeches;
    // End of variables declaration//GEN-END:variables
}
