/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.fon.silab.gui.session;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import rs.fon.silab.controllers.Controller;
import rs.fon.silab.gui.models.MemberTableModel;
import rs.fon.silab.gui.models.SessionsTableModel;
import rs.silab.domain.Member;
import rs.silab.domain.PlenarySession;

/**
 *
 * @author Branislav Vidojevic
 */
public class SessionsForm extends javax.swing.JFrame {
    
    private AddSessionForm addSessionForm;

    /**
     * Creates new form SessionsForm
     */
    public SessionsForm() {
        initComponents();
        fillSessionTable();
        tableSessions.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) {
                    fillSessionInfo();
                }
            }
        });
    }

    private void fillSessionInfo() {
        int index = tableSessions.getSelectedRow();
        SessionsTableModel model = (SessionsTableModel) tableSessions.getModel();
        PlenarySession ps = model.getSessionByIndex(index);
        if (ps == null) {
            return;
        }
        textAreaAgenda.setText(ps.getAgenda());
        TextAreaTranscript.setText(ps.getTranscriptText());
    }

    public void fillSessionTable() {
        try {
            SessionsTableModel model = new SessionsTableModel(Controller.getInstance().getSessions());
            tableSessions.setModel(model);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Couldn't get sessions from server!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAddSession = new javax.swing.JButton();
        btnUpdateSession = new javax.swing.JButton();
        btnDeleteSession = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearchSessions = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSessions = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaAgenda = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextAreaTranscript = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(140, 197));

        btnAddSession.setText("ADD");
        btnAddSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSessionActionPerformed(evt);
            }
        });

        btnUpdateSession.setText("UPDATE");
        btnUpdateSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSessionActionPerformed(evt);
            }
        });

        btnDeleteSession.setText("DELETE");
        btnDeleteSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSessionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeleteSession)
                    .addComponent(btnUpdateSession)
                    .addComponent(btnAddSession))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddSession, btnDeleteSession, btnUpdateSession});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddSession)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateSession)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteSession)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jLabel1.setText("Search for sessions");

        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtSearchSessions, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchSessions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 250));

        tableSessions.setModel(new SessionsTableModel(null));
        jScrollPane1.setViewportView(tableSessions);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(598, 180));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("AGENDA"));

        textAreaAgenda.setEditable(false);
        textAreaAgenda.setColumns(20);
        textAreaAgenda.setLineWrap(true);
        textAreaAgenda.setRows(5);
        jScrollPane2.setViewportView(textAreaAgenda);

        jPanel4.add(jScrollPane2);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("TRANSCRIPT"));

        TextAreaTranscript.setEditable(false);
        TextAreaTranscript.setColumns(20);
        TextAreaTranscript.setLineWrap(true);
        TextAreaTranscript.setRows(5);
        jScrollPane3.setViewportView(TextAreaTranscript);

        jPanel4.add(jScrollPane3);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchCriteria = txtSearchSessions.getText().trim();
        try {
            List<PlenarySession> sessions = Controller.getInstance().searchSessions(searchCriteria);
            tableSessions.setModel(new SessionsTableModel(sessions));
            if (sessions.size() > 0) {
                JOptionPane.showMessageDialog(this, "System found matching results!", "Success!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "There are no matching results!", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Coldn't get sessions from server!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSessionActionPerformed
        int index = tableSessions.getSelectedRow();
        tableSessions.getSelectionModel().clearSelection();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Select session to delete!", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            SessionsTableModel model = (SessionsTableModel) tableSessions.getModel();
            PlenarySession ps = model.getSessionByIndex(index);
            try {
                Controller.getInstance().deleteSession(ps);
                JOptionPane.showMessageDialog(this, "Session successfully deleted!", "Success!", JOptionPane.INFORMATION_MESSAGE);
                model.deleteSessionByIndex(index);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Session was not deleted!", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteSessionActionPerformed

    private void btnAddSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSessionActionPerformed
        if (addSessionForm == null || !addSessionForm.isDisplayable()) {
            addSessionForm = new AddSessionForm(this);
            addSessionForm.setVisible(true);
            addSessionForm.setLocationRelativeTo(this);
        } else {
            addSessionForm.toFront();
            addSessionForm.repaint();
        }
    }//GEN-LAST:event_btnAddSessionActionPerformed

    private void btnUpdateSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSessionActionPerformed
         int index = tableSessions.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Select session to update!", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            SessionsTableModel model = (SessionsTableModel) tableSessions.getModel();
            PlenarySession ps = model.getSessionByIndex(index);
            if (addSessionForm == null || !addSessionForm.isDisplayable()) {
                addSessionForm = new AddSessionForm(this, ps);
                addSessionForm.setVisible(true);
                addSessionForm.setLocationRelativeTo(this);
            } else {
                addSessionForm.toFront();
                addSessionForm.repaint();
            }
        }
    }//GEN-LAST:event_btnUpdateSessionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextAreaTranscript;
    private javax.swing.JButton btnAddSession;
    private javax.swing.JButton btnDeleteSession;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdateSession;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableSessions;
    private javax.swing.JTextArea textAreaAgenda;
    private javax.swing.JTextField txtSearchSessions;
    // End of variables declaration//GEN-END:variables
}
